[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/css/*"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/static/js/*"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"