app = "lifevault-demo-1756891678"
primary_region = "ord"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  NODE_ENV = "production"

[processes]
  app = "node production-backend.js"

[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "30s"
  interval = "30s"
  method = "GET"
  path = "/api/health"
  timeout = "5s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
