services:
  - type: web
    name: lifevault-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node production-backend.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://your-frontend-url.vercel.app
    healthCheckPath: /api/health 